version: '3.1'

services:
  sentry:
    image: "deviant.code:5000/sentry:3.0.0"
    user: "node"
    working_dir: /home/node/app
    restart: on-failure
    volumes:
      - ./:/home/node/app
    deploy:
      labels:
        - traefik.enable=false
    ports:
      - 7006:7006
    networks:
      - frontend
      - backend
    command: "npm run staging"

networks:
  frontend:
    external: true
  backend:
    external: true