version: '3.1'

services:
  api_tax:
    image: "darkcodz.com:5000/api/tax:1.0.0"
    user: "node"
    working_dir: /home/node/app
    restart: on-failure
    volumes:
      - ./:/home/node/app
    deploy:
      labels:
        - traefik.enable=false
    ports:
      - 9019:9019
    networks:
      - redis
      - mongo
    command: "npm run dev"

networks:
  redis:
    external: true
  mongo:
    external: true
